### ISSUE TITLE
NineChronicles.Headless ignores SIGTERM

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#806]

**Comment by moreal** [comment]
Is there a context or a way to reproduce the situation? I tried to reproduce this issue like the below scenario in my Macbook:

```bash
dotnet run -p NineChronicles.Headless.Executable -- -V "100085/6ec8E598962F1f475504F82fD5bF3410eAE58B9B/MEUCIQCSBkrb1zmrGSl7af5gBc9.GJ4iUXSBGEQDpY07+YZmmgIgU4zQb7kqr9gZU2rbUJzudZR2RHL7Odx2N594YqsBhsE=/ZHUxNjpXaW5kb3dzQmluYXJ5VXJsdTU2Omh0dHBzOi8vZG93bmxvYWQubmluZS1jaHJvbmljbGVzLmNvbS92MTAwMDg1L1dpbmRvd3MuemlwdTk6dGltZXN0YW1wdTEwOjIwMjEtMTEtMDVl" --no-miner --host localhost --genesis-block-path "https://download.nine-chronicles.com/genesis-block-9c-main" --store-type rocksdb --store-path `pwd`/here

ps -a

kill -s TERM <PID>
```

**Comment by moreal** [comment]
As a note, In Macbook macOS, it was successful to kill the headless during preloading.

**Comment by moreal** [comment]
I couldn't know a specific situation to reproduce it, but it seems to occur when `Swarm<T>` networking is hard. 
I couldn't analyze its state because its logs are too verbose.

```
[15:59:51 DBG] [Swarm] Broadcast 5479 txs...
[15:59:51 DBG] [NetMQTransport] Broadcasting message: Libplanet.Net.Messages.TxIds as 0xBEbF4d26CFa8b74f0170a86433c7aFcbE7D231C5.Unspecified/3.22.224.238:61676.124.48.176.87
[15:59:51 DBG] [NetMQTransport] Peers to broadcast: 10
[15:59:51 ERR] Unexpected exception occurred during Run. System.AggregateException: One or more errors occurred. (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Libplanet.Net.TxCompletion`2.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Net/TxCompletion.cs:line 62
   at Libplanet.Net.Swarm`1.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Net/Swarm.cs:line 204
   at Libplanet.Headless.Hosting.LibplanetNodeService`1.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Libplanet.Headless/Hosting/LibplanetNodeService.cs:line 631
   at NineChronicles.Headless.NineChroniclesNodeService.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/NineChronicles.Headless/NineChroniclesNodeService.cs:line 377
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at NineChronicles.Headless.Executable.Program.Run(String appProtocolVersionToken, String genesisBlockPath, Boolean noMiner, String host, Nullable`1 port, String swarmPrivateKeyString, Int32 minimumDifficulty, String minerPrivateKeyString, String storeType, String storePath, String[] iceServerStrings, String[] peerStrings, String[] trustedAppProtocolVersionSigners, Boolean rpcServer, String rpcListenHost, Nullable`1 rpcListenPort, Boolean graphQLServer, String graphQLHost, Nullable`1 graphQLPort, String graphQLSecretTokenPath, Boolean noCors, Int32 workers, Int32 confirmations, Boolean nonblockRenderer, Int32 nonblockRendererQueue, Int32 maximumTransactions, Boolean strictRendering, NetworkType networkType, Boolean isDev, Int32 blockInterval, Int32 reorgInterval, Boolean logActionRenders, String awsCognitoIdentity, String awsAccessKey, String awsSecretKey, String awsRegion, Boolean authorizedMiner, Int32 txLifeTime, Int32 messageTimeout, Int32 tipTimeout, Int32 demandBuffer, String[] staticPeerStrings, Int32 minerCount, Boolean skipPreload, Int32 minimumBroadcastTarget, Int32 bucketSize, String chainTipStaleBehaviorType, Int32 txQuotaPerSigner, Boolean rpcRemoteServer, Int32 pollInterval, Int32 maximumPollPeers) in /Users/moreal/github/planetarium/NineChronicles.Headless/NineChronicles.Headless.Executable/Program.cs:line 371
 ---> (Inner Exception #1) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #2) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #3) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #4) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #5) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #6) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #7) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #8) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #9) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #10) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #11) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #12) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #13) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #14) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #15) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #16) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #17) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #18) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #19) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #20) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #21) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #22) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #23) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #24) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #25) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #26) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #27) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #28) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #29) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #30) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #31) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #32) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #33) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #34) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #35) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #36) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #37) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #38) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #39) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #40) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #41) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #42) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #43) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #44) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #45) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #46) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #47) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

System.AggregateException: One or more errors occurred. (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.) (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Libplanet.Net.TxCompletion`2.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Net/TxCompletion.cs:line 62
   at Libplanet.Net.Swarm`1.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Lib9c/.Libplanet/Libplanet/Net/Swarm.cs:line 204
   at Libplanet.Headless.Hosting.LibplanetNodeService`1.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/Libplanet.Headless/Hosting/LibplanetNodeService.cs:line 631
   at NineChronicles.Headless.NineChroniclesNodeService.Dispose() in /Users/moreal/github/planetarium/NineChronicles.Headless/NineChronicles.Headless/NineChroniclesNodeService.cs:line 377
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at NineChronicles.Headless.Executable.Program.Run(String appProtocolVersionToken, String genesisBlockPath, Boolean noMiner, String host, Nullable`1 port, String swarmPrivateKeyString, Int32 minimumDifficulty, String minerPrivateKeyString, String storeType, String storePath, String[] iceServerStrings, String[] peerStrings, String[] trustedAppProtocolVersionSigners, Boolean rpcServer, String rpcListenHost, Nullable`1 rpcListenPort, Boolean graphQLServer, String graphQLHost, Nullable`1 graphQLPort, String graphQLSecretTokenPath, Boolean noCors, Int32 workers, Int32 confirmations, Boolean nonblockRenderer, Int32 nonblockRendererQueue, Int32 maximumTransactions, Boolean strictRendering, NetworkType networkType, Boolean isDev, Int32 blockInterval, Int32 reorgInterval, Boolean logActionRenders, String awsCognitoIdentity, String awsAccessKey, String awsSecretKey, String awsRegion, Boolean authorizedMiner, Int32 txLifeTime, Int32 messageTimeout, Int32 tipTimeout, Int32 demandBuffer, String[] staticPeerStrings, Int32 minerCount, Boolean skipPreload, Int32 minimumBroadcastTarget, Int32 bucketSize, String chainTipStaleBehaviorType, Int32 txQuotaPerSigner, Boolean rpcRemoteServer, Int32 pollInterval, Int32 maximumPollPeers) in /Users/moreal/github/planetarium/NineChronicles.Headless/NineChronicles.Headless.Executable/Program.cs:line 371
 ---> (Inner Exception #1) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #2) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #3) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #4) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #5) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #6) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #7) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #8) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #9) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #10) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #11) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #12) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #13) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #14) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #15) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #16) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #17) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #18) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #19) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #20) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #21) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #22) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #23) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #24) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #25) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #26) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #27) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #28) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #29) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #30) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #31) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #32) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #33) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #34) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #35) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #36) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #37) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #38) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #39) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #40) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #41) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #42) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #43) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #44) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #45) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #46) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---

 ---> (Inner Exception #47) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
info: Microsoft.Hosting.Lifetime[0]
      Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.
```

When I sent `SIGTERM` first, it tried to stop itself but it seems ignored by other `Task`s. I had sent `SIGTERM` many times and it stuck and it stopped.

**Comment by moreal** [comment]
In my research, it occurs when it was stopped at the `Libplanet.Net.TxCompletion.Dispose` by the `Task.WhenAll` line.

The situation appears rarely so I'm not sure about it. But I guess it can occur by the below scenario:

1. Cocona calls `LibplanetNodeService.Dispose()` by `SIGTERM`.
1. `LibplanetNodeService.Dispose()` calls `Swarm.Dispose()`.
1. `Swarm.Dispose()` calls `TxCompletion.Dispose()`
1. SOMETHING ~~`TxCompletion.Dispose()` calls `TxCompletion._cancellationTokenSource.Cancel()`.~~
1. `Task.WhenAll` waits forever.

**Comment by moreal** [comment]
I may find the actual reason for this issue. It is from the `NetMQQueue.Enqueue`'s infinite loop bug. Let's see all steps until calling `NetMQQueue.Enqueue`:

1. Send `SIGTERM`.
1. `SIGTERM` signal occurs calling `BackgroundService`s' `StopAsync()`
    1. `LibplanetNodeService.StopAsync()` calls `Swarm<T>.StopAsync()`
    1. `Swarm<T>.StopAsync()` calls `NetMQTransport.StopAsync()`
    1. `NetMQTransport.StopAsync()` calls `NetMQTransport._broadcastQueue.Dispose()` (i.e, `NetMQQueue<T>.Dispose`)
1. `SIGTERM` signal occurs calling `BackgroundService`s' `Dispose()`
    1. `LibplanetNodeService.Dispose()` calls `Swarm<T>.Dispose()`
    1. `Swarm<T>.Dispose()` calls `TxCompletion<T>.Dispose()`
    1. `TxCompletion<T>.Dispose()` tries to cancel all `RequestTxsFromPeerAsync` workers through `_cancellationTokenSource`.
        1. some `RequestTxsFromPeerAsync` workers will be canceled by self-checking.
        1. another `RequestTxsFromPeerAsync` workers will continue its process. So it calls `_txBroadcaster` (i.e. `Swarm<T>.BroadcastTxs` -> `Transport.BroadcastMessage` -> `NetMQQueue<T>.Enqueue`).
        
But `NetMQQueue<T>`, `_broadcastQueue` was already disposed during `NetMQTransport.StopAsync()`. And then, `NetMQQueue<T>.Enqueue` begins to run infinite loop because the internal `m_pipe` is null and it has `Infinite` timeout.

You can see the situation with the below test.

```csharp
        [Fact(Timeout = 10 * 1000)]
        public void EnqueueAfterDispose()
        {
            NetMQQueue<int> queue = new NetMQQueue<int>();

            queue.Enqueue(0);
            queue.Dispose();

            var tasks = Enumerable.Range(0, 1000).Select(x => Task.Run(async () =>
                {
                    await Task.Delay(100);
                    queue.Enqueue(100);
                }))
                .ToArray();
            Task.WaitAll(tasks);
            Assert.Equal(1, 1);
        }
```

When you ran the code, it will hang forever.

**Comment by longfin** [comment]
@moreal Thanks for detailed research. I think it may be okay to close at this moment because we'll move to `TcpTransport` in next release.

If the migration plan is delayed, or if the same issue occurs again after the transfer, please open this issue. 

cc @planetarium/libplanet
